package cz.januvojt.yahoofinance.dto

import kotlinx.serialization.Serializable

@Serializable
data class CryptoSummaryDTO(
    override val averageDailyVolume10Day: Long? = null,
    override val averageDailyVolume3Month: Long? = null,
    val circulatingSupply: Long? = null,
    val coinImageUrl: String? = null,
    override val currency: String? = null,
    override val customPriceAlertConfidence: String? = null,
    override val esgPopulated: Boolean? = null,
    override val exchange: String? = null,
    override val exchangeDataDelayedBy: Long? = null,
    override val exchangeTimezoneName: String? = null,
    override val exchangeTimezoneShortName: String? = null,
    override val fiftyDayAverage: Double? = null,
    override val fiftyDayAverageChange: Double? = null,
    override val fiftyDayAverageChangePercent: Double? = null,
    override val fiftyTwoWeekHigh: Double? = null,
    override val fiftyTwoWeekHighChange: Double? = null,
    override val fiftyTwoWeekHighChangePercent: Double? = null,
    override val fiftyTwoWeekLow: Double? = null,
    override val fiftyTwoWeekLowChange: Double? = null,
    override val fiftyTwoWeekLowChangePercent: Double? = null,
    override val fiftyTwoWeekRange: String? = null,
    override val firstTradeDateMilliseconds: Long? = null,
    val fromCurrency: String? = null,
    override val fullExchangeName: String? = null,
    override val gmtOffSetMilliseconds: Long? = null,
    override val language: String? = null,
    val lastMarket: String? = null,
    override val market: String? = null,
    val marketCap: Long? = null,
    override val marketState: String? = null,
    val messageBoardId: String? = null,
    val pageViewGrowthWeekly: Double? = null,
    override val priceHint: Int? = null,
    override val quoteSourceName: String? = null,
    override val quoteType: String? = null,
    override val region: String? = null,
    override val regularMarketChange: Double? = null,
    override val regularMarketChangePercent: Double? = null,
    override val regularMarketDayHigh: Double? = null,
    override val regularMarketDayLow: Double? = null,
    override val regularMarketDayRange: String? = null,
    override val regularMarketOpen: Double? = null,
    override val regularMarketPreviousClose: Double? = null,
    override val regularMarketPrice: Double? = null,
    override val regularMarketTime: Long? = null,
    override val regularMarketVolume: Long? = null,
    override val shortName: String? = null,
    override val sourceInterval: Int? = null,
    val startDate: Long? = null,
    override val symbol: String? = null,
    val toCurrency: String? = null,
    override val tradeable: Boolean? = null,
    override val triggerable: Boolean? = null,
    override val twoHundredDayAverage: Double? = null,
    override val twoHundredDayAverageChange: Double? = null,
    override val twoHundredDayAverageChangePercent: Double? = null,
    override val typeDisp: String? = null,
    val volume24Hr: Long? = null,
    val volumeAllCurrencies: Long? = null,
): SummaryBaseDTO