package cz.januvojt.yahoofinance.model

import cz.januvojt.yahoofinance.constants.Conversions
import cz.januvojt.yahoofinance.dto.CurrencySummaryDTO
import kotlinx.datetime.Instant
import kotlinx.datetime.TimeZone

data class CurrencySummary(
    val ask: Double? = null,
    val askSize: Int? = null,
    val averageDailyVolume10Day: Long? = null,
    val averageDailyVolume3Month: Long? = null,
    val bid: Double? = null,
    val bidSize: Int? = null,
    val currency: String? = null,
    val customPriceAlertConfidence: String? = null,
    val esgPopulated: Boolean? = null,
    val exchange: String? = null,
    val exchangeDataDelayedBy: Long? = null,
    val exchangeTimezoneName: TimeZone? = null,
    val fiftyDayAverage: Double? = null,
    val fiftyDayAverageChange: Double? = null,
    val fiftyDayAverageChangePercent: Double? = null,
    val fiftyTwoWeekHighChange: Double? = null,
    val fiftyTwoWeekHighChangePercent: Double? = null,
    val fiftyTwoWeekLowChange: Double? = null,
    val fiftyTwoWeekLowChangePercent: Double? = null,
    val fiftyTwoWeekRange: Range? = null,
    val firstTradeDate: Instant? = null,
    val fullExchangeName: String? = null,
    val language: String? = null,
    val market: String? = null,
    val marketState: String? = null,
    val messageBoardId: String? = null,
    val priceHint: Int? = null,
    val quoteSourceName: String? = null,
    val quoteType: String? = null,
    val region: String? = null,
    val regularMarketChange: Double? = null,
    val regularMarketChangePercent: Double? = null,
    val regularMarketDayRange: String? = null,
    val regularMarketOpen: Double? = null,
    val regularMarketPreviousClose: Double? = null,
    val regularMarketPrice: Double? = null,
    val regularMarketTime: Instant? = null,
    val regularMarketVolume: Long? = null,
    val shortName: String? = null,
    val sourceInterval: Int? = null,
    val symbol: String? = null,
    val tradeable: Boolean? = null,
    val triggerable: Boolean? = null,
    val twoHundredDayAverage: Double? = null,
    val twoHundredDayAverageChange: Double? = null,
    val twoHundredDayAverageChangePercent: Double? = null,
    val typeDisp: String? = null,
)

internal fun CurrencySummaryDTO.toCurrencySummary(): CurrencySummary {
    return CurrencySummary(
        this.ask,
        this.askSize,
        this.averageDailyVolume10Day,
        this.averageDailyVolume3Month,
        this.bid,
        this.bidSize,
        this.currency,
        this.customPriceAlertConfidence,
        this.esgPopulated,
        this.exchange,
        this.exchangeDataDelayedBy,
        this.exchangeTimezoneName?.let { TimeZone.of(it) },
        this.fiftyDayAverage,
        this.fiftyDayAverageChange,
        this.fiftyDayAverageChangePercent,
        this.fiftyTwoWeekHighChange,
        this.fiftyTwoWeekHighChangePercent,
        this.fiftyTwoWeekLowChange,
        this.fiftyTwoWeekLowChangePercent,
        this.fiftyTwoWeekHigh?.let { this.fiftyTwoWeekLow?.let { it1 -> Range(it, it1) } },
        this.firstTradeDateMilliseconds?.let { Instant.fromEpochMilliseconds(it) },
        this.fullExchangeName,
        this.language,
        this.market,
        this.marketState,
        this.messageBoardId,
        this.priceHint,
        this.quoteSourceName,
        this.quoteType,
        this.region,
        this.regularMarketChange,
        this.regularMarketChangePercent,
        this.regularMarketDayRange,
        this.regularMarketOpen,
        this.regularMarketPreviousClose,
        this.regularMarketPrice,
        this.regularMarketTime?.let { Instant.fromEpochSeconds(it, Conversions.MIL_TO_SEC) },
        this.regularMarketVolume,
        this.shortName,
        this.sourceInterval,
        this.symbol,
        this.tradeable,
        this.triggerable,
        this.twoHundredDayAverage,
        this.twoHundredDayAverageChange,
        this.twoHundredDayAverageChangePercent,
        this.typeDisp,
    )
}