package cz.januvojt.yahoofinance.model

import cz.januvojt.yahoofinance.constants.Conversions
import cz.januvojt.yahoofinance.dto.EtfSummaryDTO
import kotlinx.datetime.Instant
import kotlinx.datetime.TimeZone

data class EtfSummary(
    val ask: Double? = null,
    val askSize: Int? = null,
    val averageDailyVolume10Day: Long? = null,
    val averageDailyVolume3Month: Long? = null,
    val bid: Double? = null,
    val bidSize: Int? = null,
    val bookValue: Double? = null,
    val currency: String? = null,
    val customPriceAlertConfidence: String? = null,
    val dividendDate: Instant? = null,
    val epsTrailingTwelveMonths: Double? = null,
    val esgPopulated: Boolean? = null,
    val exchange: String? = null,
    val exchangeDataDelayedBy: Long? = null,
    val exchangeTimezoneName: TimeZone? = null,
    val fiftyDayAverage: Double? = null,
    val fiftyDayAverageChange: Double? = null,
    val fiftyDayAverageChangePercent: Double? = null,
    val fiftyTwoWeekHighChange: Double? = null,
    val fiftyTwoWeekHighChangePercent: Double? = null,
    val fiftyTwoWeekLowChange: Double? = null,
    val fiftyTwoWeekLowChangePercent: Double? = null,
    val fiftyTwoWeekRange: Range? = null,
    val financialCurrency: String? = null,
    val firstTradeDate: Instant? = null,
    val fullExchangeName: String? = null,
    val language: String? = null,
    val longName: String? = null,
    val market: String? = null,
    val marketCap: Long? = null,
    val marketState: String? = null,
    val messageBoardId: String? = null,
    val pageViewGrowthWeekly: Double? = null,
    val postMarketChange: Double? = null,
    val postMarketChangePercent: Double? = null,
    val postMarketPrice: Double? = null,
    val postMarketTime: Instant? = null,
    val priceHint: Int? = null,
    val priceToBook: Double? = null,
    val quoteSourceName: String? = null,
    val quoteType: String? = null,
    val region: String? = null,
    val regularMarketChange: Double? = null,
    val regularMarketChangePercent: Double? = null,
    val regularMarketDayRange: Range? = null,
    val regularMarketOpen: Double? = null,
    val regularMarketPreviousClose: Double? = null,
    val regularMarketPrice: Double? = null,
    val regularMarketTime: Instant? = null,
    val regularMarketVolume: Long? = null,
    val sharesOutstanding: Long? = null,
    val shortName: String? = null,
    val sourceInterval: Int? = null,
    val symbol: String? = null,
    val tradeable: Boolean? = null,
    val trailingAnnualDividendRate: Double? = null,
    val trailingAnnualDividendYield: Double? = null,
    val trailingPE: Double? = null,
    val trailingThreeMonthNavReturns: Double? = null,
    val trailingThreeMonthReturns: Double? = null,
    val triggerable: Boolean? = null,
    val twoHundredDayAverage: Double? = null,
    val twoHundredDayAverageChange: Double? = null,
    val twoHundredDayAverageChangePercent: Double? = null,
    val typeDisp: String? = null,
    val ytdReturn: Double? = null,
)


internal fun EtfSummaryDTO.toEtfSummary(): EtfSummary {
    return EtfSummary(
        this.ask,
        this.askSize,
        this.averageDailyVolume10Day,
        this.averageDailyVolume3Month,
        this.bid,
        this.bidSize,
        this.bookValue,
        this.currency,
        this.customPriceAlertConfidence,
        this.dividendDate?.let { Instant.fromEpochSeconds(it, Conversions.MIL_TO_SEC) },
        this.epsTrailingTwelveMonths,
        this.esgPopulated,
        this.exchange,
        this.exchangeDataDelayedBy,
        this.exchangeTimezoneName?.let { TimeZone.of(it) },
        this.fiftyDayAverage,
        this.fiftyDayAverageChange,
        this.fiftyDayAverageChangePercent,
        this.fiftyTwoWeekHighChange,
        this.fiftyTwoWeekHighChangePercent,
        this.fiftyTwoWeekLowChange,
        this.fiftyTwoWeekLowChangePercent,
        this.fiftyTwoWeekHigh?.let { this.fiftyTwoWeekLow?.let { it1 -> Range(it, it1) } },
        this.financialCurrency,
        this.firstTradeDateMilliseconds?.let { Instant.fromEpochMilliseconds(it) },
        this.fullExchangeName,
        this.language,
        this.longName,
        this.market,
        this.marketCap,
        this.marketState,
        this.messageBoardId,
        this.pageViewGrowthWeekly,
        this.postMarketChange,
        this.postMarketChangePercent,
        this.postMarketPrice,
        this.postMarketTime?.let { Instant.fromEpochSeconds(it, Conversions.MIL_TO_SEC) },
        this.priceHint,
        this.priceToBook,
        this.quoteSourceName,
        this.quoteType,
        this.region,
        this.regularMarketChange,
        this.regularMarketChangePercent,
        this.regularMarketDayHigh?.let { this.regularMarketDayLow?.let { it1 -> Range(it, it1) } },
        this.regularMarketOpen,
        this.regularMarketPreviousClose,
        this.regularMarketPrice,
        this.regularMarketTime?.let { Instant.fromEpochSeconds(it, Conversions.MIL_TO_SEC) },
        this.regularMarketVolume,
        this.sharesOutstanding,
        this.shortName,
        this.sourceInterval,
        this.symbol,
        this.tradeable,
        this.trailingAnnualDividendRate,
        this.trailingAnnualDividendYield,
        this.trailingPE,
        this.trailingThreeMonthNavReturns,
        this.trailingThreeMonthReturns,
        this.triggerable,
        this.twoHundredDayAverage,
        this.twoHundredDayAverageChange,
        this.twoHundredDayAverageChangePercent,
        this.typeDisp,
        this.ytdReturn,
    )
}