package cz.januvojt.yahoofinance.model

import cz.januvojt.yahoofinance.serializer.BigIntegerSerializer
import kotlinx.serialization.Serializable
import java.math.BigDecimal
import java.math.BigInteger

@Serializable
data class Summary(
    val ask: Double,
    val askSize: Int? = null,
    val averageAnalystRating: String? = null,
    val averageDailyVolume10Day: Int,
    val averageDailyVolume3Month: Int,
    val bid: Double,
    val bidSize: Int? = null,
    val bookValue: Double? = null,
    val currency: String,
    val customPriceAlertConfidence: String,
    val displayName: String? = null,
    val dividendDate: Int? = null,
    val earningsTimestamp: Long? = null,
    val earningsTimestampEnd: Long? = null,
    val earningsTimestampStart: Long? = null,
    val epsCurrentYear: Double? = null,
    val epsForward: Double? = null,
    val epsTrailingTwelveMonths: Double? = null,
    val esgPopulated: Boolean,
    val exchange: String,
    val exchangeDataDelayedBy: Int,
    val exchangeTimezoneName: String,
    val exchangeTimezoneShortName: String,
    val fiftyDayAverage: Double,
    val fiftyDayAverageChange: Double,
    val fiftyDayAverageChangePercent: Double,
    val fiftyTwoWeekHigh: Double,
    val fiftyTwoWeekHighChange: Double,
    val fiftyTwoWeekHighChangePercent: Double,
    val fiftyTwoWeekLow: Double,
    val fiftyTwoWeekLowChange: Double,
    val fiftyTwoWeekLowChangePercent: Double,
    val fiftyTwoWeekRange: String,
    val financialCurrency: String? = null,
    val firstTradeDateMilliseconds: Long,
    val forwardPE: Double? = null,
    val fullExchangeName: String,
    val gmtOffSetMilliseconds: Int,
    val ipoExpectedDate: String? = null,
    val language: String,
    val longName: String,
    val market: String,
    val marketCap: Long? = null,
    val marketState: String,
    val messageBoardId: String,
    val pageViewGrowthWeekly: Double? = null,
    val postMarketChange: Double? = null,
    val postMarketChangePercent: Double? = null,
    val postMarketPrice: Double? = null,
    val postMarketTime: Int? = null,
    val priceEpsCurrentYear: Double? = null,
    val priceHint: Int,
    val priceToBook: Double? = null,
    val quoteSourceName: String,
    val quoteType: String,
    val region: String,
    val regularMarketChange: Double,
    val regularMarketChangePercent: Double,
    val regularMarketDayHigh: Double,
    val regularMarketDayLow: Double,
    val regularMarketDayRange: String,
    val regularMarketOpen: Double,
    val regularMarketPreviousClose: Double,
    val regularMarketPrice: Double,
    val regularMarketTime: Int,
    val regularMarketVolume: Int,
    @Serializable(with = BigIntegerSerializer::class)
    val sharesOutstanding: BigInteger? = null,
    val shortName: String,
    val sourceInterval: Int,
    val symbol: String,
    val tradeable: Boolean,
    val trailingAnnualDividendRate: Double,
    val trailingAnnualDividendYield: Double,
    val trailingThreeMonthNavReturns: Double? = null, //
    val trailingThreeMonthReturns: Double? = null, //
    val trailingPE: Double? = null,
    val triggerable: Boolean,
    val twoHundredDayAverage: Double,
    val twoHundredDayAverageChange: Double,
    val twoHundredDayAverageChangePercent: Double,
    val typeDisp: String,
    val ytdReturn: Double? = null, //
)